spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bzh?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456   #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.184.128
    port: 6379
    database: 0